name: Integrate

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          coverage: none
          php-version: 7.4

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Run friendsofphp/php-cs-fixer
        run: vendor/bin/php-cs-fixer fix --config=.php_cs --diff --diff-format=udiff --dry-run --verbose

  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Run tests
        run: vendor/bin/phpunit --verbose
